name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install Packages
              run: bun install
            - name: Lint
              run: bun run lint
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x, 22.x]
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Packages
              run: bun install
            - name: Test
              run: bun test
    test-for-other-version:
        name: "Test for Stylelint ${{ matrix.stylelint }} on Node.js ${{ matrix.node-version }}"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
                stylelint: ["14", "15"]
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Target Packages
              run: |+
                  bun add -d stylelint@${{ matrix.stylelint }}
                  rm -rf node_modules
            - name: Install Packages
              run: bun install
            - name: Test
              run: bun test
